### ISSUE TITLE
[BUG] wrong port for webcam stream referenced in web_interface source file

### ISSUE THREAD

**Issue by Life0fBrian** [chillibasket/walle-replica#22]
I followed the script https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-MJPEG-Streamer-Install-&-Setup-&-FFMpeg-Recording#manager-script for setting up the manager script of the mjpg_streamer and it by default uses webcam port 8080.
However when starting the Wall-e web interface I was not able to get a webcam stream. After checking the stream object of the web interface I noticed it points to port 8081.

After checking **_/home/pi/walle-replica/web_interface/static/js/main.js_** I noticed in line 61 column 129 that it says 8081.
I changed it to 8080 and now I can reactivate the webcam stream in the web interface without any problem.
Maybe you can correct it in the source files.

The source files show a Camera tab but at least I don't have it and the stream does not automatically start upon web interface loading.
I'm using a cheap USB webcam and not the Raspi Cam but I don't know whether this causes the missing Camera tab or not.

**Comment by chillibasket** [comment]
Hi, thanks for reporting this issue. 

Looking at the change log for the script which shows how to set up the mjpegstreamer, the port number appears to have been changed from 8081 to 8080 in July: https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-MJPEG-Streamer-Install-&-Setup-&-FFMpeg-Recording/_history

I will update the Wall-E code to reflect this new change once I get some time next week.

**Comment by Life0fBrian** [comment]
Hi,

thank you very much for taking care on that!
I'm used to use port 8080 due to OctoPrint so I did not think about the manager script being the wrong part here.
Otherwise there is at least one more error in it:

At first it says:
`UV="yes"`

But later it checks:
`if [ "${YUV}" == "true" ]; then
	INPUT_OPTIONS+=" -y"
fi`

But that is not your business!

If you don't mind one last question: 
Should the web stream automatically start after logging in into the web interface or does it require reactivating the MJPG Streamer?

And thanks for the whole Wall-e project! :)

**Comment by chillibasket** [comment]
Yes that YUV="yes" does seem to be a bug as well. Perhaps I should post the instructions and script directly in my instructions instead of linking to the external repository which is subject to change.

Currently the webcam and the Arduino connection don't start automatically; you always have to click the start buttons. Something like that definitely would be useful; you can open up a second issue with a feature request.

**Comment by chillibasket** [comment]
This issue has now been resolved in commit b7151d11c1f634db419f8722705dfed9da471212
