### ISSUE TITLE
[FR] autostart web stream and connecting to Arduino upon successful login on web interface

### ISSUE THREAD

**Issue by Life0fBrian** [chillibasket/walle-replica#23]
It would be a nice to have feature that after you successfully logged in into the web interface the webcam stream if properly set up before starts automatically.
Additionally it would be great to automatically connect to the Arduino as well.
Of course you can click on reactivate mjpg_streamer and connect to Arduino but if all has been properly set up before this would improve the usability and user experience.
You can just load the web interface an steer your Wall-e. :)

Maybe you will find some time soon to implement it.

Thank you very much!

**Comment by chillibasket** [comment]
I've added this feature now in commit e96ce814143a3e7298cfb6225679b0c0c0349ddf. I've tested it on my Wall-E and it seems to work, but let me know if you come across any issues. To enable auto-start, see the new user-variables in *app.py*

**Comment by Life0fBrian** [comment]
Sorry to come back here but it does not seem to work at least for my Wall-e.
I deleted the old **walle-replica** directory and cloned the new git release, set up the password and **autoStartCamera = True**.
Additionally the mjpg-streamer.sh script has been recreated following the updated instructions here.

But now when I (re)boot the RasPi and login into the web interface the stream does not load automatically.
It only loads after I hit the reactivate MJPG Streamer button twice. Same when I just open the web interface in a new browser tab.
However the **autoStartArduino** feature works, even with no Arduino connected. So the scripts should be OK in general.

Maybe you could check it if you find some time.
If you require some files from my side just give me a ping.

**Comment by chillibasket** [comment]
Ok the fact that you have to press the button twice means that the stream has started successfully, but the web interface does not update to show it. 

Make sure to clear the cookies/cache in you browser, or use the incognito window. The script which is used to show the stream is a Javascript file, and often the browser keeps using the old version even after an update.

**Comment by Life0fBrian** [comment]
Shame over my head, it is working like a charme! 
Deleted just cookies and everything related to those data and that fixed my issue.

Thank you very much for your fast response and great support.
