### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by myMartek** [chillibasket/walle-replica#29]
Hi,

I have installed the Webinterface on my RaspberryPI 4 with 64bit Raspberry PI OS.

I also added the startup script to automatically start the webinterface but unfortunately the web interface will not autostart.

The error message I got from journalctl is:

`Nov 22 20:50:57 walle walle[4494]: pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Nov 22 20:50:57 walle walle[4494]: Hello from the pygame community. https://www.pygame.org/contribute.html
Nov 22 20:50:57 walle walle[4494]: Traceback (most recent call last):
Nov 22 20:50:57 walle walle[4494]:   File "/home/pi/walle-replica/web_interface/app.py", line 37, in <module>
Nov 22 20:50:57 walle walle[4494]:     pygame.mixer.init()
Nov 22 20:50:57 walle walle[4494]: pygame.error: ALSA: Couldn't open audio device: Unknown error 524
Nov 22 20:50:57 walle systemd[1]: walle.service: Main process exited, code=exited, status=1/FAILURE
Nov 22 20:50:57 walle systemd[1]: walle.service: Failed with result 'exit-code'.`

I found out that the same error comes whenever I run the script with sudo or as another user for example. I have absolutely no clue why it is not working on startup. Do you have any idea?

**Comment by dkrey** [comment]
You need to add this environment variable to your systemd service
Environment=XDG_RUNTIME_DIR=/run/user/1000

This is my working unit file.

```
[Unit]
Description=Wall-E Web Interface
After=network.target

[Service]
Environment=XDG_RUNTIME_DIR=/run/user/1000
WorkingDirectory=/home/wall-e/walle-replica/web_interface
ExecStart=/usr/bin/python3 app.py
KillSignal=SIGINT
Restart=always
User=wall-e
Group=wall-e

[Install]
WantedBy=multi-user.target
```

(edit: corrected the KillSignal)

**Comment by w45354** [comment]
I applied the autostart settings. it can autostart but only if a monitor is connected. Has anyone met this issue before?

**Comment by dkrey** [comment]
Fortunately it works fine for me.
 
What's the output of journalctl?
`journalctl -u walle`

**Comment by TheBanshee71** [comment]
im having the same problem. Any ideas? IM new to this...Thanks
![autostart error](https://github.com/chillibasket/walle-replica/assets/147000546/aca1440b-ec47-4e6f-8497-baa04c23a239)

**Comment by chillibasket** [comment]
@TheBanshee71 your error appears to be different. It says in the error message "failed at step USER" which means that the user name defined in the "walle.service" file is wrong. This is most likely due to using a different username than the default if "pi". Try updating the file with your actual username

**Comment by TheBanshee71** [comment]
I found the problem, The username is pi but it didn't have correct permissions. But now I'm getting an cannot start audio device error.

**Comment by TheBanshee71** [comment]
this is the only error im getting now
pygame.error: ALSA: Couldn't open audio device: Unknown error 524
Ive googled it with no luck. Any ideas? Thanks

**Comment by dkrey** [comment]
Do you get audio if you start the webinterface manually as user pi?
If so, do the error happen again if you run the webinterface as root or via sudo?

If that's the case, you just need to add the env var to the unit file and reload it, just as I mentioned above.
`sudo nano /etc/systemd/system/walle.service` 
 Add this line below [Service]
`Environment=XDG_RUNTIME_DIR=/run/user/1000`

Reload the unit file
`sudo systemctl daemon-reload`

Restart the interface
`sudo systemctl restart walle`

Check the logs
`journalctl -u walle`

**Comment by TheBanshee71** [comment]
I had added that before with no luck, but I re-installed everything and this time it worked!! Thanks
