### ISSUE TITLE
sounds fail to play

### ISSUE THREAD

**Issue by w45354** [chillibasket/walle-replica#31]
all of the sounds were OK to play at the beginning, but when I finished all the settings, the sounds could not be played anymore. what might be the issue?

**Comment by dkrey** [comment]
A wild guess could be that your pi decided to use a different audio out than before.
Can you play the local .ogg files via aplay? 
You could also check amixer to set the volume and make sure nothing got muted.

**Comment by w45354** [comment]
the sound issue may be due to this(shown in the picture). 
![e07b0c89d4c003fd42c2012dd2e8f8e](https://github.com/chillibasket/walle-replica/assets/157502002/e8cc1fe4-32f0-4305-b293-93fd4764bbfd)
what does it mean by this error? also, with this error, I will meet problems when logging onto the web interface

**Comment by dkrey** [comment]
Yeah, this error prevents the interface from working correctly. 
For some reason your raspberry has problems accessing the usb-serial port to the arduino. If you did change to the code, it might help resetting the git repo and start over.  In case you're fine with losing all changes to the code, enter  
`git reset --hard` in the walle-replica directory.
Afterwards you'd need to set the config in app.y again of course.

But maybe that's not even necessary. You could edit app.py, modify the variables arduinoPort and autoStartArduino:
`arduinoPort = "ttyACM0"`
`autoStartArduino = True`

If that also doesn't help, it might be interesting if you arduino is actually detected by the raspi. So next try this and see if the Arduino is listed there.
`lsusb`

**Comment by w45354** [comment]
the interface issue is tackled. But sounds are still not played. And I am sure the sounds can be played straight away on my RPI, and it is not muted. When I play the sounds through the web interface, no error pops up.
![b015425d7c8d9bc97b2257e9e934a86](https://github.com/chillibasket/walle-replica/assets/157502002/5f8ba58f-8d5a-4976-b66e-97ea36e5f46f)

**Comment by w45354** [comment]
I totally reimaged my RPI, now the sounds are OK to play.

**Comment by w45354** [comment]
again, the sound is not working after I finish Automatically start Server on Boot setting. Maybe something happening during the camera stream phase or auto-start phase causes the sound issue?

**Comment by dkrey** [comment]
Does it work again when you manually start the webserver?

Also what's the output of journalctl right after you log in the webinterface?
`journalctl -u walle`

**Comment by w45354** [comment]
still not working when manually starting. the journal is like this.
![1](https://github.com/chillibasket/walle-replica/assets/157502002/0e4bcce8-75fd-4125-b573-90f40d456b21)
![2](https://github.com/chillibasket/walle-replica/assets/157502002/c1a47066-032f-48a2-ba55-725f12243c50)
![3](https://github.com/chillibasket/walle-replica/assets/157502002/f3b2e3f3-d1b5-4830-8ec4-e188570144f8)
![4](https://github.com/chillibasket/walle-replica/assets/157502002/f125f46a-e0ec-4957-b19d-9b013c5b844e)

**Comment by dkrey** [comment]
Is this a recent 64bit raspberry pi os you're using? At least the original systemd unit file should throw this error `pygame.error: No available audio device`. Also mjpg streamer seems to be running for you (which is good but not common 😄  )

For the second test I meant: what happens if you start the interface in user context. Do you get sound again?
like `pi@walle$ python3 ~/walle-replica/web_interface/app.py`

And a last question, can you play audio in terminal? 
`pw-play ~/walle-replica/web_interface/static/sounds/Sound_Ohhh_1850.ogg`

(replace pw-play with something like ogg123, if you don't have it installed)

**Comment by w45354** [comment]
it's so weird, sometimes work sometimes not. I guess, if any possibility that the ports of the speaker and camera conflict. as my speaker is a little special, it has a jack output and a USB power supply. and also, my camera is a USB one rather official one. maybe changing hardware would tackle this issue.

**Comment by dkrey** [comment]
Hmm - could it be that the speaker draws too much power from your pi? Or does it add another sounddevice via usb so the pi doesn't know which one to use? You use `alsamixer` via terminal to check if there's anything muted or what the current  audio outputdevice is.
