### ISSUE TITLE
Will you kindly share 3d model design file instead of STL?

### ISSUE THREAD

**Issue by hyansuper** [chillibasket/walle-replica#5]
Hi,
I love the Wall-E so much and I am printing the parts. I'd like to make the eyes look more alive by separating "eyebrows" from the eye frame and make it manually posable or movable by servos.
Would you like to share editable design files?

**Comment by chillibasket** [comment]
I plan to release all the files in *.STEP format which should make the design easier to modify. I'm busy with college at the moment (my dissertation is due next month), but I'll probably upload the files to Thingiverse or my website after that.

**Comment by chillibasket** [comment]
The STEP files are now available at https://wired.chillibasket.com/3d-printed-wall-e/
