### ISSUE TITLE
No servo movement possible in Arduino IDE serial window

### ISSUE THREAD

**Issue by Hagelstein** [chillibasket/walle-replica#6]
Hi!
Have the electronics now so far that I get the movements of the drive with the web interface controlled. Only the servo motors will not move when I try to control them in the Arduino IDE in the serial window.
The movements of the drive function with 'w', 'a', 's' or 'd' works well.
Only the servo control with 'j', 'l', 'i' or 'k' does not react.

Is this due to the fact that the calibration of the servos is not yet possible/done, or did I destroy the Adafruit PWM servo board? I use the library 1.0.2 for the PWM servo board.

Sincerely

**Comment by chillibasket** [comment]
Dupplicate question. The response is provided on my website: https://wired.chillibasket.com/3d-printed-wall-e/#comment-374
